Cw/Cw/Models/Place.cs
using System.Collections.Generic;

namespace Cw.Models
{
    public class Place
    {
        public string Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string MainPhotoPath { get; set; }
        public List<Photos> Photos { get; set; }
        public List<Reviews> Reviews { get; set; }
        public List<Rate> Rates { get; set; }

    }
}

Cw/Cw/Models/PlacesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace Cw.Models
{
    public class PlacesViewModel
    {
        public string Description { get; set; }
        public string Name { get; set; }
        public string MainPhotoPath { get; set; }
        public IFormFile Photo { get; set; }
        public List<Place> Places { get; set; }
    }
}

Cw/Cw/Controllers/PlaceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Cw.Data;
using Cw.Models;
using Cw.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Cw.Controllers
{
    public class PlaceController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment _environment;
        private readonly UploadFileService _fileUploadService;

        public PlaceController(ApplicationDbContext db, IHostingEnvironment environment, UploadFileService fileUploadService)
        {
            _db = db;
            _environment = environment;
            _fileUploadService = fileUploadService;
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddPlace(PlacesViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    string path = Path.Combine(_environment.WebRootPath,$"images\\");
                    string photoPath = $"/images/{model.Photo.FileName}";
                    _fileUploadService.Upload(path, model.Photo.FileName, model.Photo);
                    Place place = new Place
                    {
                        Name = model.Name,
                        MainPhotoPath = photoPath,
                        Description = model.Description
                    };
                    
                    _db.Places.Add(place);
                    _db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AddPlace()
        {
            PlacesViewModel model = new PlacesViewModel();
            return View(model);
        }

        public IActionResult PlaceDetails(string placeId)
        {
            Place model = _db.Places.FirstOrDefault(p => p.Id == placeId);
            model.Photos = _db.Photos.Where(p => p.PlaceId == model.Id).ToList();
            model.Rates = _db.Rates.Where(r => r.PlaceId == model.Id).ToList();
            model.Reviews = _db.Reviews.Where(rw => rw.PlaceId == model.Id).ToList();
            return View(model);
        }

        public IActionResult FindPlaceByName(string Name)
        {
            List<Place> places = _db.Places.Where(p => p.Name.Contains(Name)).ToList();
            foreach (var place in places)
            {
                place.Photos = _db.Photos.Where(p => p.PlaceId == place.Id).ToList();
                place.Reviews = _db.Reviews.Where(rw => rw.PlaceId == place.Id).ToList();
            }
            return View(places);
        }
    }
}

Cw/Cw/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Cw.Data;
using Cw.Models;
using Cw.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Cw.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment _environment;
        private readonly UploadFileService _fileUploadService;

        public ReviewController(ApplicationDbContext db, IHostingEnvironment environment, UploadFileService fileUploadService)
        {
            _db = db;
            _environment = environment;
            _fileUploadService = fileUploadService;
        }

        public IActionResult AddReview(string Review, double Rate, string UserId, string PlaceId)
        {
            var user = _db.Users.FirstOrDefault(u => u.Id == UserId);
            Reviews review = new Reviews
            {
                Review = Review,
                Rate = Rate,
                PlaceId = PlaceId,
                UserId = UserId,
                UserName = user.UserName,
                ReviewDate = DateTime.Now
            };
            _db.Reviews.Add(review);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult UploadPlacePhoto(IFormFile Photo, string UserId, string PlaceId)
        {
            string path = Path.Combine(_environment.WebRootPath, $"images\\");
            string photoPath = $"/images/{Photo.FileName}";
            _fileUploadService.Upload(path, Photo.FileName, Photo);
            Photos photo = new Photos
            {
                FilePath = photoPath,
                PlaceId = PlaceId,
                UserId = UserId
            };
            _db.Photos.Add(photo);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Cw/Cw/Views/Place/AddPlace.cshtml
@model Cw.Models.PlacesViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2 class="text-center">Добавить заведение</h2>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div style="padding: 10px; margin-top: 10px; border: 1px solid silver; border-radius: 5px;">
            <form asp-action="AddPlace" asp-controller="Place" method="post" enctype="multipart/form-data">
                <p>Название заведения</p>
                <input type="text" asp-for="Name" class="form-control"/>
                <p>Описание заведения </p>
                <textarea asp-for="Description" class="form-control" rows="5" style="width: 100%; resize: none;"></textarea>
                <input type="file" class="form-group" asp-for="Photo" style="border: none; margin-top: 10px;"/>
                <button type="submit" class="btn btn-default center-block">Создать</button>
            </form>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>

Cw/Cw/Views/Place/FindPlaceByName.cshtml
@model System.Collections.Generic.List<Cw.Models.Place>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Результаты поиска</h2>
<div class="row">
    <div class="col-md-12">
        @if (@Model.Count == 0)
        {
            <h2 class="text-center">По заданному имени нет заведений</h2>
        }
        else
        {
            foreach (var place in @Model)
            {
                <div class="place_style">
                    <a asp-action="PlaceDetails" asp-controller="Place" asp-route-placeId ="@place.Id">
                        <img style="width: 100%; margin-bottom: 5px;" src="@place.MainPhotoPath"/>
                        <span>@place.Name</span>
                    </a>
                    <p>
                        ( @if (@place.Reviews.Count > 0)
                          {
                              @place.Reviews.Average(x => x.Rate)
                          }
                          else
                          {
                              <span>0</span>
                          }
                        | @place.Reviews.Count отзывов )
                    </p>
                    <p>@place.Photos.Count фото</p>
                </div>
            }
        }
    </div>
</div>
<style>
    .place_style {
        width: 300px;
        padding: 10px;
        margin: 7px;
        float: left;
        border: 1px solid silver;
        border-radius: 5px;
    }
</style>

Cw/Cw/Views/Place/PlaceDetails.cshtml
@model Place
@inject Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@{
    ViewData["Title"] = "PlaceDetails";
}


<div class="row" style="margin-top: 10px;">
    <div class="col-md-7">
        <h3>@Model.Name</h3>
        <div>@Model.Description</div>
    </div>
    <div class="col-md-5">
        <img src="@Model.MainPhotoPath" style="width: 98%;" />
    </div>
    <div class="col-md-12" style="border-bottom: 1px solid black; margin-bottom: 10px;">
        @if (@Model.Photos.Count > 0)
        {
            foreach (var photo in @Model.Photos)
            {
                <p style="width: 180px; float: left; padding: 5px; margin: 10px;">
                    <img style="width: 100%;" src="@photo.FilePath" />
                </p>
            }
        }
        else
        {
            <p>Дополнительные фотографии не загружены</p>
        }
    </div>
    <div class="col-md-12" style="border-bottom: 1px solid black; margin-bottom: 10px;">
        Рейтинг заведения
        @if (@Model.Reviews.Count > 0)
        {
            @Model.Reviews.Average(x => x.Rate)
        }
        else
        {
            <span>0</span>
        }
    </div>
    <div class="col-md-12">
        <h3>Отзывы</h3>
        @if (@Model.Reviews.Count > 0)
        {
            foreach (var review in @Model.Reviews)
            {
                <div style="padding: 10px; border: 1px solid silver; margin: 7px;">
                    <div>@review.ReviewDate.ToShortDateString() <b>@review.UserName</b> написал:</div>
                    <div>@review.Review</div>
                    <div>Оценка: @Math.Round(@review.Rate, 2)</div>
                </div>
            }
        }
        else
        {
            <p>Отзывов еще не было</p>
        }
        @if (SignInManager.IsSignedIn(User))
        {
            <div style="margin-top: 5px; border-top: 1px solid silver;">
                <form method="post" asp-action="AddReview" asp-controller="Review">
                    <h3>Добавить отзыв</h3>
                    <textarea name="Review" class="form-control" rows="5" style="width: 90%; resize: none;" placeholder="Текст вашего отзыва"></textarea>
                    <label for="rate">
                        <select class="form-control" name="Rate" id="rate">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                    </label>
                    <input type="hidden" value="@Model.Id" name="PlaceId" />
                    <input type="hidden" name="UserId" value="@UserManager.GetUserAsync(User).Result.Id" />
                    <button type="submit" class="btn btn-default">Отправить</button>
                </form>
            </div>
            <div style="margin-top: 15px;">
                <form method="post" asp-action="UploadPlacePhoto" asp-controller="Review" enctype="multipart/form-data">
                    <p>Загрузите фото данного места</p>
                    <input type="file" class="form-control" name="Photo">
                    <input type="hidden" value="@Model.Id" name="PlaceId" />
                    <input type="hidden" name="UserId" value="@UserManager.GetUserAsync(User).Result.Id" />
                    <button type="submit" class="btn btn-default">Отправить</button>
                </form>
            </div>
        }
        else
        {
            <p>Добавлять отзывы и фото могут только авторизованные пользователи</p>
        }
    </div>
</div>